apiVersion: apps/v1
kind: Deployment
metadata:
  name: library_management-deployment
spec:
  replicas: 1  # You can adjust this based on how many instances you want
  selector:
    matchLabels:
      app: library_management
  template:
    metadata:
      labels:
        app: library_management
    spec:
      containers:
      - name: library_management
        image: archit3000/library_management:latest
        ports:
        - containerPort: 3000  # Adjust based on your app's port
---
apiVersion: v1
kind: Service
metadata:
  name: library_management-service
spec:
  selector:
    app: library_management
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80
      targetPort: 3000  # Adjust based on your app's port
  type: NodePort  # This is for Minikube, it will expose it externally
